//! Phase C (roadmap v2.1): the differential-equivalence instance of the
//! verdict core, at the MSM boundary of ragu.
//!
//! This crate is the second of the two live instances that earn
//! `scribe-core` (locked decision 3). Its subject —
//! `{ reference, candidate, inputs }`, a pair of computations plus an input
//! distribution — is deliberately nothing like a `CircuitIR`. It implements
//! `Claim`, `Oracle`, and `Corpus` against `scribe-core` with zero changes to
//! that crate.
//!
//! The oracle is boringly thin on purpose (locked decision 4): run both
//! computations on every input, accept iff all outputs match, reject on any
//! mismatch, and return `Undetermined` on a panic — a crash is evidence of a
//! crash, not proof of inequivalence. The interesting work is in the versioned
//! corpora. `corpus/msm/` records the original fuzz-fleet measurement
//! (`docs/v2.1/equivalence-notes.md`), while `corpus/msm-pr842/` records the
//! size support of ragu PR #842's direct MSM equivalence strategy. Each
//! includes a planted mutant outside its input distribution so `validate()`
//! reports an escape instead of allowing a green result to imply unmeasured
//! discriminating power.

use std::panic::{catch_unwind, AssertUnwindSafe};
use std::sync::Arc;

use group::{Curve, Group};
use serde::{Deserialize, Serialize};

use scribe_core::{Claim, Corpus, Diagnostics, Evidence, Instance, Oracle, Outcome, Reason};

pub mod vendored_msm;

pub use vendored_msm::{bucket_lookup, msm_naive, msm_reference, msm_with_defect, Defect};

/// The concrete curve the corpus instantiates `msm` with — Pallas, the host
/// curve of ragu's `Pasta` cycle.
pub type Scalar = pasta_curves::pallas::Scalar;
/// Affine Pallas point (the MSM bases).
pub type Affine = pasta_curves::pallas::Affine;
/// Projective Pallas point (the MSM output).
pub type Point = pasta_curves::pallas::Point;

/// A computation at the MSM boundary: scalars and bases in, curve point out.
pub type MsmFn = fn(&[Scalar], &[Affine]) -> Point;

/// Which implementation boundary an [`EquivalenceClaim`] is drawn at. Only
/// the MSM boundary exists today; it is one of the narrow comparison
/// boundaries named in ragu #834 (MSM results, (s)-evaluations, polynomial
/// commitments, Poseidon outputs, proof digests) — and of those, the only one
/// that is externally reachable and needs no serializer that does not exist
/// yet (`Proof` has none; ragu #660).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Boundary {
    /// `ragu_arithmetic::util::msm`.
    Msm,
}

/// The claim: two implementations are equivalent at a boundary, over an
/// input distribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EquivalenceClaim {
    /// The comparison boundary.
    pub boundary: Boundary,
}

impl Claim for EquivalenceClaim {
    type Subject = EquivalenceSubject;

    fn kind(&self) -> &'static str {
        "implementation-equivalence"
    }

    fn describe(&self) -> String {
        match self.boundary {
            Boundary::Msm => "reference and candidate MSM implementations produce identical \
                              results over the input distribution"
                .to_string(),
        }
    }
}

/// The subject of an [`EquivalenceClaim`]: a reference computation, a
/// candidate computation, and the inputs on which they must agree.
pub struct EquivalenceSubject {
    /// The trusted computation.
    pub reference: MsmFn,
    /// The computation under adjudication.
    pub candidate: MsmFn,
    /// The input distribution both are run on.
    pub inputs: MsmInputs,
}

/// A deterministic input distribution: for each size `n` in `sizes`, the
/// first `n` scalars and bases of a seeded pool.
///
/// The pool is shared (`Arc`) across corpus instances: scalars are full-width
/// (all 255 bits exercised, so every window segment of every `bucket_lookup`
/// band selected by these sizes is populated), generated by a splitmix64
/// sequence; bases are the non-identity points `G, 2G, 3G, ...`.
#[derive(Clone)]
pub struct MsmInputs {
    /// MSM sizes, one comparison per size.
    pub sizes: Vec<usize>,
    pool: Arc<InputPool>,
}

struct InputPool {
    scalars: Vec<Scalar>,
    bases: Vec<Affine>,
}

fn splitmix64(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

impl MsmInputs {
    /// Generates the pool for `sizes` from `seed`. The pool length is the
    /// largest size requested.
    pub fn generate(seed: u64, sizes: Vec<usize>) -> Self {
        let n = sizes.iter().copied().max().unwrap_or(0);
        let mut state = seed;
        let scalars: Vec<Scalar> = (0..n)
            .map(|_| {
                let w0 = splitmix64(&mut state);
                let w1 = splitmix64(&mut state);
                let w2 = splitmix64(&mut state);
                let w3 = splitmix64(&mut state);
                // Little-endian limbs, reduced mod q: full-width scalars, so
                // every window segment of every band is populated.
                Scalar::from_raw([w0, w1, w2, w3])
            })
            .collect();

        let g = Point::generator();
        let mut acc = g;
        let projectives: Vec<Point> = (0..n)
            .map(|_| {
                let p = acc;
                acc += g;
                p
            })
            .collect();
        let mut bases = vec![Affine::default(); n];
        Point::batch_normalize(&projectives, &mut bases);

        MsmInputs {
            sizes,
            pool: Arc::new(InputPool { scalars, bases }),
        }
    }

    /// The scalar/base slices for one size.
    fn slice(&self, n: usize) -> (&[Scalar], &[Affine]) {
        (&self.pool.scalars[..n], &self.pool.bases[..n])
    }

    #[cfg(test)]
    pub(crate) fn test_slice(&self, n: usize) -> (&[Scalar], &[Affine]) {
        self.slice(n)
    }
}

/// The thin differential oracle: outputs equal on every input → `Accept`;
/// any mismatch → `Reject`; any panic → `Undetermined`.
pub struct DifferentialOracle;

impl Oracle<EquivalenceClaim> for DifferentialOracle {
    fn adjudicate(&self, claim: &EquivalenceClaim, subject: &EquivalenceSubject) -> Outcome {
        debug_assert!(matches!(claim.boundary, Boundary::Msm));
        let mut mismatched = Vec::new();
        for &n in &subject.inputs.sizes {
            let (coeffs, bases) = subject.inputs.slice(n);
            let reference = subject.reference;
            let candidate = subject.candidate;
            let r = catch_unwind(AssertUnwindSafe(|| reference(coeffs, bases)));
            let c = catch_unwind(AssertUnwindSafe(|| candidate(coeffs, bases)));
            match (r, c) {
                (Ok(r), Ok(c)) => {
                    if r != c {
                        mismatched.push(n);
                    }
                }
                _ => {
                    return Outcome::Undetermined(Reason {
                        summary: format!(
                            "an implementation panicked at n = {n}; a crash is not proof of \
                             inequivalence"
                        ),
                    });
                }
            }
        }
        if mismatched.is_empty() {
            Outcome::Accept(Evidence {
                summary: format!(
                    "outputs identical on all {} input sizes",
                    subject.inputs.sizes.len()
                ),
                details: vec![format!("sizes: {:?}", subject.inputs.sizes)],
            })
        } else {
            Outcome::Reject(Diagnostics {
                summary: format!("outputs diverge at {} input size(s)", mismatched.len()),
                details: vec![format!("diverging sizes: {mismatched:?}")],
            })
        }
    }
}

/// A correct-by-construction candidate for the corpus positive: the same
/// windowed algorithm run with a deliberately different window width than
/// `bucket_lookup` selects (different bucket counts, segment counts, and
/// window boundaries — any fixed `c` computes the same sum). Comparing it to
/// the reference is a metamorphic check, so the positive is not a vacuous
/// self-comparison. It stays fast at every fleet-measured size, unlike the
/// textbook [`msm_naive`], which the unit tests use at small sizes instead.
pub fn msm_shifted_window(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    let selected = bucket_lookup(coeffs.len());
    let c = if selected > 1 {
        selected - 1
    } else {
        selected + 1
    };
    vendored_msm::msm_windowed_with_c(coeffs, bases, c)
}

fn mutant_wide_window_skip_double(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    msm_with_defect(coeffs, bases, Defect::WideWindowSkipDouble)
}

fn mutant_bucket_collision_drop(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    msm_with_defect(coeffs, bases, Defect::BucketCollisionDrop)
}

fn mutant_window_shift_drop(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    msm_with_defect(coeffs, bases, Defect::WindowShiftDrop)
}

fn mutant_add_base_at_size(coeffs: &[Scalar], bases: &[Affine], size: usize) -> Point {
    let mut result = msm_reference(coeffs, bases);
    if coeffs.len() == size {
        result += bases[0];
    }
    result
}

fn mutant_pr842_8104_add_base(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    mutant_add_base_at_size(coeffs, bases, 8104)
}

fn mutant_pr842_8192_add_base(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    mutant_add_base_at_size(coeffs, bases, 8192)
}

fn reference(coeffs: &[Scalar], bases: &[Affine]) -> Point {
    msm_reference(coeffs, bases)
}

/// Resolves a manifest candidate name to its implementation.
pub fn candidate_by_name(name: &str) -> Option<MsmFn> {
    Some(match name {
        "shifted-window" => msm_shifted_window,
        "naive" => msm_naive::<Affine>,
        "mutant-wide-window-skip-double" => mutant_wide_window_skip_double,
        "mutant-bucket-collision-drop" => mutant_bucket_collision_drop,
        "mutant-window-shift-drop" => mutant_window_shift_drop,
        "mutant-pr842-8104-add-base" => mutant_pr842_8104_add_base,
        "mutant-pr842-8192-add-base" => mutant_pr842_8192_add_base,
        _ => return None,
    })
}

/// One corpus entry as recorded in a versioned MSM manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestEntry {
    /// Stable instance id.
    pub id: String,
    /// Candidate implementation name, resolved via [`candidate_by_name`].
    pub candidate: String,
    /// Why this entry exists.
    pub description: String,
}

/// A versioned MSM corpus manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    /// Corpus version (locked decision 5: corpora are versioned artifacts).
    pub version: String,
    /// The ragu revision the reference was vendored from.
    pub ragu_revision: String,
    /// Seed for the deterministic input pool.
    pub pool_seed: u64,
    /// The input distribution: MSM sizes exposed to every corpus candidate.
    pub input_sizes: Vec<usize>,
    /// Instances the oracle must accept.
    pub positives: Vec<ManifestEntry>,
    /// Instances the oracle must reject.
    pub negatives: Vec<ManifestEntry>,
}

/// `Corpus<EquivalenceClaim>` backed by a versioned MSM manifest.
pub struct MsmCorpus {
    manifest: Manifest,
    inputs: MsmInputs,
}

impl MsmCorpus {
    /// Loads the corpus from a manifest JSON string and materializes the
    /// shared input pool.
    pub fn from_manifest_str(json: &str) -> Result<Self, String> {
        let manifest: Manifest =
            serde_json::from_str(json).map_err(|e| format!("corpus manifest: {e}"))?;
        for entry in manifest.positives.iter().chain(&manifest.negatives) {
            if candidate_by_name(&entry.candidate).is_none() {
                return Err(format!(
                    "corpus manifest: unknown candidate '{}' in entry '{}'",
                    entry.candidate, entry.id
                ));
            }
        }
        let inputs = MsmInputs::generate(manifest.pool_seed, manifest.input_sizes.clone());
        Ok(MsmCorpus { manifest, inputs })
    }

    /// Loads `corpus/msm/manifest.json` from the repository checkout this
    /// crate lives in.
    pub fn load_default() -> Result<Self, String> {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../corpus/msm/manifest.json"
        );
        Self::load_file(path)
    }

    /// Loads the corpus modeling ragu PR #842's MSM size-strategy support.
    pub fn load_pr842() -> Result<Self, String> {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../corpus/msm-pr842/manifest.json"
        );
        Self::load_file(path)
    }

    fn load_file(path: &str) -> Result<Self, String> {
        let json = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
        Self::from_manifest_str(&json)
    }

    /// The parsed manifest.
    pub fn manifest(&self) -> &Manifest {
        &self.manifest
    }

    fn instances(&self, entries: &[ManifestEntry]) -> Vec<Instance<EquivalenceClaim>> {
        entries
            .iter()
            .map(|entry| Instance {
                id: entry.id.as_str().into(),
                claim: EquivalenceClaim {
                    boundary: Boundary::Msm,
                },
                subject: EquivalenceSubject {
                    reference,
                    candidate: candidate_by_name(&entry.candidate).expect("validated at load time"),
                    inputs: self.inputs.clone(),
                },
            })
            .collect()
    }
}

impl Corpus<EquivalenceClaim> for MsmCorpus {
    fn negatives(&self) -> Vec<Instance<EquivalenceClaim>> {
        self.instances(&self.manifest.negatives)
    }

    fn positives(&self) -> Vec<Instance<EquivalenceClaim>> {
        self.instances(&self.manifest.positives)
    }

    fn version(&self) -> &str {
        &self.manifest.version
    }
}
