import ZkGadgets.Field
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# edwards-addition

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  add_x : x3 + 168696 * x3 * x1 * x2 * y1 * y2 - x1 * y2 - y1 * x2 = 0
  add_y : y3 - 168696 * y3 * x1 * x2 * y1 * y2 - y1 * y2 + 168700 * x1 * x2 = 0

Soundness: 168700 * x3 * x3 + y3 * y3 = 1 + 168696 * x3 * x3 * y3 * y3

Proof strategy:
  1. Extract x3*(1+D) = A and y3*(1-D) = B from constraints
  2. Square to get x3²*Dp² = A² and y3²*E² = B²
  3. Prove the denominator-cleared identity a*A²*E² + B²*Dp² = Dp²*E² + d*A²*B²
     using the curve equations for (x1,y1) and (x2,y2)
  4. Combine to show G*Dp²*E² = 0, then cancel the nonzero factor
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem edwards_addition_sound
    (x1 y1 x2 y2 x3 y3 : ZMod p)
    (h_on_curve_1 : (168700 : ZMod p) * x1 * x1 + y1 * y1 = 1 + (168696 : ZMod p) * x1 * x1 * y1 * y1)
    (h_on_curve_2 : (168700 : ZMod p) * x2 * x2 + y2 * y2 = 1 + (168696 : ZMod p) * x2 * x2 * y2 * y2)
    (h_nondeg_x : (1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2 ≠ 0)
    (h_nondeg_y : (1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2 ≠ 0)
    (h_add_x : x3 + 168696 * x3 * x1 * x2 * y1 * y2 - x1 * y2 - y1 * x2 = 0)
    (h_add_y : y3 - 168696 * y3 * x1 * x2 * y1 * y2 - y1 * y2 + 168700 * x1 * x2 = 0)
    : 168700 * x3 * x3 + y3 * y3 = 1 + 168696 * x3 * x3 * y3 * y3 := by
  -- Step 1: From constraints, extract the multiplication forms
  -- x3 * (1 + d*x1*x2*y1*y2) = x1*y2 + y1*x2
  have hx3 : x3 * ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) =
      x1 * y2 + y1 * x2 := by linear_combination h_add_x
  -- y3 * (1 - d*x1*x2*y1*y2) = y1*y2 - a*x1*x2
  have hy3 : y3 * ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) =
      y1 * y2 - (168700 : ZMod p) * x1 * x2 := by linear_combination h_add_y
  -- Step 2: Square both to eliminate x3, y3 from products
  -- x3² * (1+D)² = A²
  have hx3_sq : x3 * x3 * (((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
      ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) =
      (x1 * y2 + y1 * x2) * (x1 * y2 + y1 * x2) := by
    calc x3 * x3 * (((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2))
        = (x3 * ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) *
          (x3 * ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) := by ring
      _ = (x1 * y2 + y1 * x2) * (x1 * y2 + y1 * x2) := by rw [hx3]
  -- y3² * (1-D)² = B²
  have hy3_sq : y3 * y3 * (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
      ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) =
      (y1 * y2 - (168700 : ZMod p) * x1 * x2) * (y1 * y2 - (168700 : ZMod p) * x1 * x2) := by
    calc y3 * y3 * (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2))
        = (y3 * ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) *
          (y3 * ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) := by ring
      _ = (y1 * y2 - (168700 : ZMod p) * x1 * x2) *
          (y1 * y2 - (168700 : ZMod p) * x1 * x2) := by rw [hy3]
  -- x3²*y3² * (1+D)²*(1-D)² = A²*B²
  have hxy : x3 * x3 * (y3 * y3) *
      (((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
       ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) *
      (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
       ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) =
      (x1 * y2 + y1 * x2) * (x1 * y2 + y1 * x2) *
      ((y1 * y2 - (168700 : ZMod p) * x1 * x2) *
       (y1 * y2 - (168700 : ZMod p) * x1 * x2)) := by
    linear_combination
      y3 * y3 * (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) * hx3_sq +
      (x1 * y2 + y1 * x2) * (x1 * y2 + y1 * x2) * hy3_sq
  -- Step 3: The polynomial identity for the denominator-cleared curve equation
  -- a*A²*E² + B²*Dp² = Dp²*E² + d*A²*B²  (using curve equations for inputs)
  have h_goal_mult :
      (168700 : ZMod p) * ((x1 * y2 + y1 * x2) * (x1 * y2 + y1 * x2)) *
        (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
         ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) +
      ((y1 * y2 - (168700 : ZMod p) * x1 * x2) *
       (y1 * y2 - (168700 : ZMod p) * x1 * x2)) *
        (((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
         ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) =
      ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
         ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) +
      (168696 : ZMod p) * ((x1 * y2 + y1 * x2) * (x1 * y2 + y1 * x2)) *
        ((y1 * y2 - (168700 : ZMod p) * x1 * x2) *
         (y1 * y2 - (168700 : ZMod p) * x1 * x2)) := by
    linear_combination
      ((168696 : ZMod p) * x2 * y2 *
        (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) * (x1 * y1 - x2 * y2) +
         (y1 * y2 - (168700 : ZMod p) * x1 * x2) * (x1 * y2 - y1 * x2)) +
       ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((168700 : ZMod p) * x2 * x2 + y2 * y2)) * h_on_curve_1 +
      (-(168696 : ZMod p) * x1 * y1 *
        (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) * (x1 * y1 - x2 * y2) +
         (y1 * y2 - (168700 : ZMod p) * x1 * x2) * (x1 * y2 - y1 * x2)) +
       ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
        ((1 : ZMod p) + (168696 : ZMod p) * x1 * x1 * y1 * y1)) * h_on_curve_2
  -- Step 4: Combine to show G * Dp² * E² = 0
  have h_key :
      ((168700 : ZMod p) * x3 * x3 + y3 * y3 - 1 -
       (168696 : ZMod p) * x3 * x3 * (y3 * y3)) *
      (((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
       ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) *
      (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
       ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) = 0 := by
    linear_combination
      (168700 : ZMod p) *
        (((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
         ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2)) * hx3_sq +
      (((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
       ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2)) * hy3_sq -
      (168696 : ZMod p) * hxy +
      h_goal_mult
  -- Step 5: Since Dp² * E² ≠ 0, conclude G = 0
  have hDp2_ne : ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) *
      ((1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2) ≠ 0 :=
    mul_ne_zero h_nondeg_x h_nondeg_x
  have hE2_ne : ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) *
      ((1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2) ≠ 0 :=
    mul_ne_zero h_nondeg_y h_nondeg_y
  have h_zero : (168700 : ZMod p) * x3 * x3 + y3 * y3 - 1 -
      (168696 : ZMod p) * x3 * x3 * (y3 * y3) = 0 := by
    rcases mul_eq_zero.mp h_key with h_left | h_right
    · rcases mul_eq_zero.mp h_left with hG | hDp2
      · exact hG
      · exact absurd hDp2 hDp2_ne
    · exact absurd h_right hE2_ne
  -- Step 6: Convert G = 0 to the goal equality
  linear_combination h_zero

-- Soundness gate: this proof rests only on the trusted kernel axioms.
#audit_axioms edwards_addition_sound
