import ZkGadgets.Field
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod

/-!
# nonzero-check

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  inverse : x * x_inv - (1 : ZMod p) = 0

Soundness: x ≠ 0
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem nonzero_check_sound
    (x x_inv : ZMod p)
    (h_inverse : x * x_inv - (1 : ZMod p) = 0)
    : x ≠ 0 := by
  intro h_zero
  have hmul : x * x_inv = 1 := sub_eq_zero.mp h_inverse
  rw [h_zero, zero_mul] at hmul
  exact one_ne_zero hmul.symm

-- Soundness gate: this proof rests only on the trusted kernel axioms.
#audit_axioms nonzero_check_sound
