import ZkGadgets.Field
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# poseidon-sbox

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  square_1 : q - x * x = 0
  square_2 : r - q * q = 0
  output : y - r * x = 0

Soundness: y = x ^ 5
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem poseidon_sbox_sound
    (x q r y : ZMod p)
    (h_square_1 : q - x * x = 0)
    (h_square_2 : r - q * q = 0)
    (h_output : y - r * x = 0)
    : y = x ^ 5 := by
  have hq : q = x * x := by linear_combination h_square_1
  have hr : r = q * q := by linear_combination h_square_2
  have hy : y = r * x := by linear_combination h_output
  rw [hy, hr, hq]
  ring

-- Soundness gate: this proof rests only on the trusted kernel axioms.
#audit_axioms poseidon_sbox_sound
-- Verdict-engine probes (C2/C3): y = 1 with x = 0 refutes the conclusion; the
-- squaring chain at x = 2 in ZMod 7 (q = 4, r = 2, y = 4) satisfies every constraint.
#audit_falsifiable poseidon_sbox_sound (p := 7) (x := 0) (y := 1)
#audit_satisfiable poseidon_sbox_sound (p := 7) (x := 2) (q := 4) (r := 2) (y := 4)
