import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# ragu-boolean

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  g0_mul : w1 * w2 - w3 = 0
  g0_aux : w3 * one = 0
  g1_mul : w4 * w5 - w6 = 0
  g1_aux : w6 * w7 = 0
  lc0 : w6 = 0
  lc1 : one - w4 - w5 = 0
  out0_bind : w4 - out0 = 0
  one_is_1 : one - (1 : ZMod p) = 0

Soundness: out0 = 0 ∨ out0 = 1

This is the Phase B (roadmap v2.1) proof target: the constraint system was
extracted from `ragu_primitives::Boolean::alloc` through frontend-ragu's
structure-only Driver (ragu rev fc61822c), including the gate's hidden
`C·D = 0` constraint (`g1_aux`) and the SYSTEM gate whose `D` wire is the
`one` wire (`g0_aux`). `out0` is the verifier-visible instance (a `k(Y)`
coefficient); everything else is private.

Proof idea: `g1_mul` + `lc0` give `w4 * w5 = 0`; a prime field has no zero
divisors, so `w4 = 0` or `w5 = 0`. In the first case `out0 = w4 = 0`; in the
second, `lc1` and `one_is_1` force `w4 = one - w5 = 1`, so `out0 = 1`.
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

-- The extraction records the complete constraint system; this spec does not
-- need every constraint (the SYSTEM-gate pair and the boolean gate's spare
-- D-wire constraint are not load-bearing), so silence the unused-binder lint
-- rather than diverge from the machine-generated statement.
set_option linter.unusedVariables false

theorem ragu_boolean_sound
    (out0 : ZMod p)
    (one w1 w2 w3 w4 w5 w6 w7 : ZMod p)
    (h_g0_mul : w1 * w2 - w3 = 0)
    (h_g0_aux : w3 * one = 0)
    (h_g1_mul : w4 * w5 - w6 = 0)
    (h_g1_aux : w6 * w7 = 0)
    (h_lc0 : w6 = 0)
    (h_lc1 : one - w4 - w5 = 0)
    (h_out0_bind : w4 - out0 = 0)
    (h_one_is_1 : one - (1 : ZMod p) = 0)
    : out0 = 0 ∨ out0 = 1 := by
  have hmul : w4 * w5 = 0 := by linear_combination h_g1_mul + h_lc0
  rcases mul_eq_zero.mp hmul with h | h
  · left
    linear_combination h - h_out0_bind
  · right
    linear_combination -h_out0_bind - h_lc1 + h_one_is_1 - h

#audit_axioms ragu_boolean_sound  -- proof must rest only on the trusted kernel axioms
