import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# add-gate

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  add : x + y - z = 0

Soundness: z = x + y
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem add_gate_sound
    (x y z : ZMod p)
    (h_add : x + y - z = 0)
    : z = x + y := by
  linear_combination -h_add
#audit_axioms add_gate_sound  -- proof must rest only on the trusted kernel axioms
