import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# boolean-check

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  boolean : b * b - b = 0

Soundness: b = 0 ∨ b = 1
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem boolean_check_sound
    (b : ZMod p)
    (h_boolean : b * b - b = 0)
    : b = 0 ∨ b = 1 := by
have h : b * (b - 1) = 0 := by linear_combination h_boolean
rcases mul_eq_zero.mp h with h0 | h1
· left; exact h0
· right; linear_combination h1
#audit_axioms boolean_check_sound  -- proof must rest only on the trusted kernel axioms
