import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# ragu-boolean

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  g0_mul : w1 * w2 - w3 = 0
  g0_aux : w3 * one = 0
  g1_mul : w4 * w5 - w6 = 0
  g1_aux : w6 * w7 = 0
  lc0 : w6 = 0
  lc1 : one - w4 - w5 = 0
  out0_bind : w4 - out0 = 0
  one_is_1 : one - (1 : ZMod p) = 0

Soundness: out0 = 0 ∨ out0 = 1
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem ragu_boolean_sound
    (out0 : ZMod p)
    (one w1 w2 w3 w4 w5 w6 w7 : ZMod p)
    (h_g0_mul : w1 * w2 - w3 = 0)
    (h_g0_aux : w3 * one = 0)
    (h_g1_mul : w4 * w5 - w6 = 0)
    (h_g1_aux : w6 * w7 = 0)
    (h_lc0 : w6 = 0)
    (h_lc1 : one - w4 - w5 = 0)
    (h_out0_bind : w4 - out0 = 0)
    (h_one_is_1 : one - (1 : ZMod p) = 0)
    : out0 = 0 ∨ out0 = 1 := by
  have hone : one = 1 := by linear_combination h_one_is_1
  have hsum : w4 + w5 = 1 := by linear_combination -h_lc1 + h_one_is_1
  have hprod : w4 * w5 = 0 := by linear_combination h_g1_mul + h_lc0
  rcases mul_eq_zero.mp hprod with h4 | h5
  · left
    linear_combination -h_out0_bind + h4
  · right
    linear_combination hsum - h5 - h_out0_bind
#audit_axioms ragu_boolean_sound  -- proof must rest only on the trusted kernel axioms
