import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# inverse-gate — refutation target

Auto-generated by lean-emit (refutation mode). Do not edit the theorem statement.

A kernel-accepted proof of this theorem is a concrete counterexample at
`p = 5`: witness values satisfying every constraint while violating the
spec. That refutes the generic soundness statement — the circuit is
under-constrained (or the spec is wrong).

Constraints:
  inverse : x * x_inv - x_inv = 0

Spec under attack: x ≠ 0
-/

theorem inverse_gate_refuted
    : ¬ (∀ (x x_inv : ZMod 5),
        x * x_inv - x_inv = 0 →
        (x ≠ 0)) := by
intro h
exact (h 0 0 (by decide)) rfl
#audit_axioms inverse_gate_refuted  -- proof must rest only on the trusted kernel axioms
