import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# zero-indicator — refutation target

Auto-generated by lean-emit (refutation mode). Do not edit the theorem statement.

A kernel-accepted proof of this theorem is a concrete counterexample at
`p = 5`: witness values satisfying every constraint while violating the
spec. That refutes the generic soundness statement — the circuit is
under-constrained (or the spec is wrong).

Constraints:
  completeness : x * x_inv + out - (1 : ZMod p) = 0

Spec under attack: (x = 0 ∧ out = 1) ∨ (x ≠ 0 ∧ out = 0)
-/

theorem zero_indicator_refuted
    : ¬ (∀ (x x_inv out : ZMod 5),
        x * x_inv + out - (1 : ZMod 5) = 0 →
        ((x = 0 ∧ out = 1) ∨ (x ≠ 0 ∧ out = 0))) := by
intro h
have := h 1 4 2 (by decide)
revert this
decide
#audit_axioms zero_indicator_refuted  -- proof must rest only on the trusted kernel axioms
