import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# range-check-2bit — refutation target

Auto-generated by lean-emit (refutation mode). Do not edit the theorem statement.

A kernel-accepted proof of this theorem is a concrete counterexample at
`p = 5`: witness values satisfying every constraint while violating the
spec. That refutes the generic soundness statement — the circuit is
under-constrained (or the spec is wrong).

Constraints:
  bit_0 : b0 * b0 - b0 = 0
  decomposition : b0 + 2 * b1 - x = 0

Spec under attack: ZMod.val x < 4
-/

theorem range_check_2bit_refuted
    : ¬ (∀ (x b0 b1 : ZMod 5),
        5 > 4 →
        b0 * b0 - b0 = 0 →
        b0 + 2 * b1 - x = 0 →
        (ZMod.val x < 4)) := by
intro h
have := h 4 0 2 (by decide) (by decide) (by decide)
revert this
decide
#audit_axioms range_check_2bit_refuted  -- proof must rest only on the trusted kernel axioms
