import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# swap-pair — refutation target

Auto-generated by lean-emit (refutation mode). Do not edit the theorem statement.

A kernel-accepted proof of this theorem is a concrete counterexample at
`p = 5`: witness values satisfying every constraint while violating the
spec. That refutes the generic soundness statement — the circuit is
under-constrained (or the spec is wrong).

Constraints:
  boolean : b * b - b = 0
  mux1 : out1 - in1 + b * in1 - b * in2 = 0

Spec under attack: (b = 0 ∧ out1 = in1 ∧ out2 = in2) ∨ (b = 1 ∧ out1 = in2 ∧ out2 = in1)
-/

theorem swap_pair_refuted
    : ¬ (∀ (b in1 in2 out1 out2 : ZMod 5),
        b * b - b = 0 →
        out1 - in1 + b * in1 - b * in2 = 0 →
        ((b = 0 ∧ out1 = in1 ∧ out2 = in2) ∨ (b = 1 ∧ out1 = in2 ∧ out2 = in1))) := by
intro h
have := h 0 0 1 0 2 (by decide) (by decide)
revert this
decide
#audit_axioms swap_pair_refuted  -- proof must rest only on the trusted kernel axioms
