use gadget_ir::Gadget;

/// Emit a Lean 4 source file from a gadget definition.
///
/// The output contains:
/// - Imports
/// - Variable declarations (prime field, witnesses)
/// - Constraint hypotheses
/// - Soundness theorem statement with `sorry`
pub fn emit_lean(gadget: &Gadget) -> String {
    let mut out = String::new();

    out.push_str("import Mathlib.Data.ZMod.Basic\n");
    out.push_str("import Mathlib.Data.Fin.Basic\n");
    out.push_str("import Mathlib.Algebra.BigOperators.Group.Finset\n");
    out.push_str("\n");

    // Header comment
    out.push_str(&format!("/-!\n# {}\n", gadget.name));
    out.push_str("-- Auto-generated by lean-emit. Do not edit the theorem statement.\n");
    out.push_str("-/\n\n");

    // Prime field parameter
    out.push_str("variable (p : ℕ) [Fact (Nat.Prime p)]\n\n");

    // Theorem statement with sorry
    out.push_str("-- TODO: emit full theorem from IR\n");
    out.push_str("-- This is a skeleton. Full emit logic is built in week 2.\n");

    if let Some(spec) = &gadget.soundness_spec {
        out.push_str(&format!("-- Soundness spec: {}\n", spec));
    }

    out.push_str("\n#check ZMod\n");

    out
}
