use std::collections::{HashMap, HashSet};

use gadget_ir::{Constraint, Gadget, Term};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    InvalidIdentifier { kind: &'static str, name: String },
    DuplicateWitnessId(usize),
    UnknownWitnessId { constraint: String, id: usize },
    DuplicateConstraintLabel(String),
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::InvalidIdentifier { kind, name } => {
                write!(f, "invalid Lean identifier for {}: {}", kind, name)
            }
            EmitError::DuplicateWitnessId(id) => write!(f, "duplicate witness id: {}", id),
            EmitError::UnknownWitnessId { constraint, id } => {
                write!(
                    f,
                    "constraint {} references unknown witness id {}",
                    constraint, id
                )
            }
            EmitError::DuplicateConstraintLabel(label) => {
                write!(f, "duplicate generated constraint label: {}", label)
            }
        }
    }
}

impl std::error::Error for EmitError {}

/// Emit a Lean 4 proof scaffold from a gadget definition.
///
/// The output contains imports, witness parameters, constraint hypotheses,
/// and a `sorry` proof. The theorem statement is machine-generated;
/// the proof is left for a human or LLM to fill in.
pub fn emit_lean(gadget: &Gadget) -> Result<String, EmitError> {
    let witness_names: Vec<&str> = gadget.witnesses.iter().map(|w| w.name.as_str()).collect();
    let witness_by_id = witness_map(gadget)?;
    let theorem_name = format!("{}_sound", sanitize_generated_ident(&gadget.name, "gadget"));
    let constraint_labels = generated_constraint_labels(gadget)?;

    let mut out = String::new();

    // -- imports
    out.push_str("import ZkGadgets.Field\n");
    out.push_str("import Mathlib.Data.ZMod.Basic\n");
    out.push_str("import Mathlib.Algebra.Field.ZMod\n\n");

    // -- doc comment
    out.push_str(&format!("/-!\n# {}\n\n", gadget.name));
    out.push_str("Auto-generated by lean-emit. Do not edit the theorem statement.\n\n");
    out.push_str("Constraints:\n");
    for c in &gadget.constraints {
        out.push_str(&format!(
            "  {} : {} = 0\n",
            c.label,
            emit_constraint_expr(c, &witness_by_id)?
        ));
    }
    if let Some(spec) = &gadget.soundness_spec {
        out.push_str(&format!("\nSoundness: {}\n", spec));
    }
    out.push_str("-/\n\n");

    // -- field variable
    out.push_str("variable (p : ℕ) [Fact (Nat.Prime p)]\n\n");

    // -- theorem
    out.push_str(&format!("theorem {}\n", theorem_name));

    // witness parameters
    out.push_str(&format!("    ({} : ZMod p)\n", witness_names.join(" ")));

    // extra hypotheses (e.g. field-size bounds)
    for h in &gadget.hypotheses {
        out.push_str(&format!("    ({} : {})\n", h.name, h.lean_type));
    }

    // constraint hypotheses
    for (c, label) in gadget.constraints.iter().zip(constraint_labels.iter()) {
        let expr = emit_constraint_expr(c, &witness_by_id)?;
        out.push_str(&format!("    (h_{} : {} = 0)\n", label, expr));
    }

    // conclusion
    let conclusion = match &gadget.soundness_spec {
        Some(spec) => format!("    : {}", spec),
        None => "    : True".to_string(),
    };
    out.push_str(&conclusion);
    out.push_str(" := by\n  sorry\n");

    Ok(out)
}

/// Render a constraint as a Lean expression (without `= 0`).
fn emit_constraint_expr(
    c: &Constraint,
    witness_by_id: &HashMap<usize, &str>,
) -> Result<String, EmitError> {
    if c.terms.is_empty() {
        return Ok("0".to_string());
    }

    let mut parts = Vec::new();
    for (i, term) in c.terms.iter().enumerate() {
        parts.push(emit_term(term, witness_by_id, &c.label, i == 0)?);
    }
    Ok(parts.join(" "))
}

/// Render a single term with sign handling.
///
/// `is_first` controls whether a leading `+` is suppressed.
fn emit_term(
    term: &Term,
    witness_by_id: &HashMap<usize, &str>,
    constraint: &str,
    is_first: bool,
) -> Result<String, EmitError> {
    let coeff = term.coeff.trim();
    let negative = coeff.starts_with('-');
    let abs_coeff = if negative { &coeff[1..] } else { coeff };

    // monomial: product of witness names
    let monomial: Option<String> = if term.vars.is_empty() {
        None
    } else {
        let mut var_names = Vec::with_capacity(term.vars.len());
        for &id in &term.vars {
            let name =
                witness_by_id
                    .get(&id)
                    .copied()
                    .ok_or_else(|| EmitError::UnknownWitnessId {
                        constraint: constraint.to_string(),
                        id,
                    })?;
            var_names.push(name);
        }
        Some(var_names.join(" * "))
    };

    // absolute expression (no sign)
    let expr = match (abs_coeff, &monomial) {
        ("1", Some(m)) => m.clone(),
        (c, Some(m)) => format!("{} * {}", c, m),
        ("1", None) => "(1 : ZMod p)".to_string(),
        (c, None) => format!("({} : ZMod p)", c),
    };

    // attach sign
    if is_first {
        if negative {
            Ok(format!("-({})", expr))
        } else {
            Ok(expr)
        }
    } else if negative {
        Ok(format!("- {}", expr))
    } else {
        Ok(format!("+ {}", expr))
    }
}

fn witness_map(gadget: &Gadget) -> Result<HashMap<usize, &str>, EmitError> {
    let mut witness_by_id = HashMap::with_capacity(gadget.witnesses.len());
    let mut witness_names = HashSet::with_capacity(gadget.witnesses.len());

    for witness in &gadget.witnesses {
        validate_user_ident("witness", &witness.name)?;
        if witness_by_id
            .insert(witness.id, witness.name.as_str())
            .is_some()
        {
            return Err(EmitError::DuplicateWitnessId(witness.id));
        }
        if !witness_names.insert(witness.name.as_str()) {
            return Err(EmitError::InvalidIdentifier {
                kind: "duplicate witness",
                name: witness.name.clone(),
            });
        }
    }

    for h in &gadget.hypotheses {
        validate_user_ident("hypothesis", &h.name)?;
    }

    Ok(witness_by_id)
}

fn generated_constraint_labels(gadget: &Gadget) -> Result<Vec<String>, EmitError> {
    let mut seen = HashSet::with_capacity(gadget.constraints.len());
    let mut labels = Vec::with_capacity(gadget.constraints.len());

    for constraint in &gadget.constraints {
        let label = sanitize_generated_ident(&constraint.label, "constraint");
        if !seen.insert(label.clone()) {
            return Err(EmitError::DuplicateConstraintLabel(label));
        }
        labels.push(label);
    }

    Ok(labels)
}

fn validate_user_ident(kind: &'static str, name: &str) -> Result<(), EmitError> {
    if is_valid_lean_ident(name) {
        Ok(())
    } else {
        Err(EmitError::InvalidIdentifier {
            kind,
            name: name.to_string(),
        })
    }
}

fn sanitize_generated_ident(input: &str, fallback: &str) -> String {
    let mut out = String::new();
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    while out.contains("__") {
        out = out.replace("__", "_");
    }

    let out = out.trim_matches('_');
    let mut out = if out.is_empty() {
        fallback.to_string()
    } else {
        out.to_string()
    };

    if out.as_bytes().first().is_some_and(u8::is_ascii_digit) || is_lean_keyword(&out) {
        out.insert_str(0, fallback);
        out.insert(fallback.len(), '_');
    }

    out
}

fn is_valid_lean_ident(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }

    if is_lean_keyword(name) {
        return false;
    }

    chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '\'')
}

fn is_lean_keyword(name: &str) -> bool {
    matches!(
        name,
        "abbrev"
            | "axiom"
            | "by"
            | "class"
            | "def"
            | "deriving"
            | "do"
            | "else"
            | "end"
            | "example"
            | "extends"
            | "for"
            | "forall"
            | "fun"
            | "have"
            | "if"
            | "import"
            | "in"
            | "inductive"
            | "infix"
            | "instance"
            | "let"
            | "macro"
            | "match"
            | "mutual"
            | "namespace"
            | "open"
            | "opaque"
            | "partial"
            | "private"
            | "protected"
            | "section"
            | "set_option"
            | "structure"
            | "syntax"
            | "theorem"
            | "unsafe"
            | "variable"
            | "where"
            | "with"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use gadget_ir::WitnessVar;

    fn examples_dir() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .join("examples")
    }

    #[test]
    fn emit_range_check() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("range-check/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();

        // has theorem with correct name
        assert!(out.contains("theorem range_check_8bit_sound"));
        // has all witnesses
        assert!(out.contains("(x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)"));
        // bit constraint renders correctly: b0 * b0 - b0 = 0
        assert!(out.contains("h_bit_0 : b0 * b0 - b0 = 0"));
        // decomposition has weighted terms
        assert!(out.contains("h_decomposition :"));
        assert!(out.contains("128 * b7"));
        assert!(out.contains("- x = 0"));
        // ends with sorry
        assert!(out.contains("sorry"));
        // soundness spec in conclusion
        assert!(out.contains("∃ k : Fin 256"));
    }

    #[test]
    fn emit_conditional_select() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("conditional-select/gadget.toml"))
                .unwrap();
        let out = emit_lean(&gadget).unwrap();

        assert!(out.contains("theorem conditional_select_sound"));
        assert!(out.contains("(b x y z : ZMod p)"));
        // boolean constraint: b * b - b = 0
        assert!(out.contains("h_boolean : b * b - b = 0"));
        // select constraint: b * x + y - b * y - z = 0
        assert!(out.contains("h_select : b * x + y - b * y - z = 0"));
        assert!(out.contains("sorry"));
    }

    #[test]
    fn emit_poseidon_sbox() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("poseidon-sbox/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem poseidon_sbox_sound"));
        assert!(out.contains("(x q r y : ZMod p)"));
        assert!(out.contains("h_square_1 : q - x * x = 0"));
        assert!(out.contains("h_square_2 : r - q * q = 0"));
        assert!(out.contains("h_output : y - r * x = 0"));
        assert!(out.contains("y = x ^ 5"));
    }

    #[test]
    fn emit_nonzero_check() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("nonzero-check/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem nonzero_check_sound"));
        assert!(out.contains("h_inverse : x * x_inv - (1 : ZMod p) = 0"));
        assert!(out.contains("x ≠ 0"));
    }

    #[test]
    fn emit_edwards_addition() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("edwards-addition/gadget.toml"))
                .unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem edwards_addition_sound"));
        assert!(out.contains("(x1 y1 x2 y2 x3 y3 : ZMod p)"));
        // hypotheses before constraints
        assert!(out.contains("h_on_curve_1"));
        assert!(out.contains("h_on_curve_2"));
        assert!(out.contains("h_add_x"));
        assert!(out.contains("h_add_y"));
        assert!(out.contains("168700"));
    }

    #[test]
    fn emit_range_check_with_hypothesis() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("range-check/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("(hp : p > 256)"));
        // hypothesis appears before constraints
        let hp_pos = out.find("hp : p > 256").unwrap();
        let hbit_pos = out.find("h_bit_0").unwrap();
        assert!(hp_pos < hbit_pos);
    }

    #[test]
    fn emits_terms_by_witness_id_not_position() {
        let gadget = Gadget {
            name: "out-of-order".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![
                WitnessVar {
                    id: 10,
                    name: "x".to_string(),
                },
                WitnessVar {
                    id: 3,
                    name: "y".to_string(),
                },
            ],
            constraints: vec![Constraint {
                label: "product".to_string(),
                terms: vec![Term {
                    coeff: "1".to_string(),
                    vars: vec![3, 10],
                }],
            }],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("h_product : y * x = 0"));
    }

    #[test]
    fn rejects_unknown_witness_id() {
        let gadget = Gadget {
            name: "bad-ref".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x".to_string(),
            }],
            constraints: vec![Constraint {
                label: "missing".to_string(),
                terms: vec![Term {
                    coeff: "1".to_string(),
                    vars: vec![1],
                }],
            }],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let err = emit_lean(&gadget).unwrap_err();
        assert!(matches!(err, EmitError::UnknownWitnessId { id: 1, .. }));
    }

    #[test]
    fn rejects_invalid_user_identifier() {
        let gadget = Gadget {
            name: "bad-ident".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x-bad".to_string(),
            }],
            constraints: vec![],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let err = emit_lean(&gadget).unwrap_err();
        assert!(matches!(
            err,
            EmitError::InvalidIdentifier {
                kind: "witness",
                ..
            }
        ));
    }

    #[test]
    fn sanitizes_generated_identifiers() {
        let gadget = Gadget {
            name: "8-bit gadget!".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x".to_string(),
            }],
            constraints: vec![Constraint {
                label: "select-value!".to_string(),
                terms: vec![Term {
                    coeff: "1".to_string(),
                    vars: vec![0],
                }],
            }],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem gadget_8_bit_gadget_sound"));
        assert!(out.contains("h_select_value : x = 0"));
    }
}
