use std::collections::{HashMap, HashSet};

use gadget_ir::{Constraint, Gadget, Term};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EmitError {
    InvalidIdentifier { kind: &'static str, name: String },
    DuplicateWitnessId(usize),
    UnknownWitnessId { constraint: String, id: usize },
    DuplicateConstraintLabel(String),
    MissingSpec,
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::InvalidIdentifier { kind, name } => {
                write!(f, "invalid Lean identifier for {}: {}", kind, name)
            }
            EmitError::DuplicateWitnessId(id) => write!(f, "duplicate witness id: {}", id),
            EmitError::UnknownWitnessId { constraint, id } => {
                write!(
                    f,
                    "constraint {} references unknown witness id {}",
                    constraint, id
                )
            }
            EmitError::DuplicateConstraintLabel(label) => {
                write!(f, "duplicate generated constraint label: {}", label)
            }
            EmitError::MissingSpec => {
                write!(f, "gadget has no soundness_spec — nothing to refute")
            }
        }
    }
}

impl std::error::Error for EmitError {}

/// Emit a decomposed Lean 4 proof scaffold with helper lemmas.
///
/// For gadgets with multiple constraints, this emits intermediate helper lemmas
/// that break the proof into smaller steps the LLM can tackle independently.
/// Each constraint gets a lemma that extracts a useful equality from `expr = 0`.
/// The main theorem then uses these helpers.
pub fn emit_lean_decomposed(gadget: &Gadget) -> Result<String, EmitError> {
    // Only decompose if there are ≥2 constraints and a soundness spec
    if gadget.constraints.len() < 2 || gadget.soundness_spec.is_none() {
        return emit_lean(gadget);
    }

    let witness_names: Vec<&str> = gadget.witnesses.iter().map(|w| w.name.as_str()).collect();
    let witness_by_id = witness_map(gadget)?;
    let gadget_ident = sanitize_generated_ident(&gadget.name, "gadget");
    let theorem_name = format!("{}_sound", gadget_ident);
    let constraint_labels = generated_constraint_labels(gadget)?;

    let mut out = String::new();

    // -- imports
    out.push_str("import ZkGadgets.Field\n");
    out.push_str("import ZkGadgets.Audit\n");
    out.push_str("import Mathlib.Data.ZMod.Basic\n");
    out.push_str("import Mathlib.Algebra.Field.ZMod\n");
    // The tactics the system prompt teaches (`linear_combination`, `ring`) must
    // be importable, or every model proof fails with "unknown tactic".
    out.push_str("import Mathlib.Tactic.Ring\n");
    out.push_str("import Mathlib.Tactic.LinearCombination\n\n");

    // -- doc comment
    out.push_str(&format!("/-!\n# {}\n\n", gadget.name));
    out.push_str(
        "Auto-generated by lean-emit (decomposed mode). Do not edit the theorem statement.\n\n",
    );
    out.push_str("Constraints:\n");
    for c in &gadget.constraints {
        out.push_str(&format!(
            "  {} : {} = 0\n",
            c.label,
            emit_constraint_expr(c, &witness_by_id)?
        ));
    }
    if let Some(spec) = &gadget.soundness_spec {
        out.push_str(&format!("\nSoundness: {}\n", spec));
    }
    out.push_str("-/\n\n");

    // -- field variable
    out.push_str("variable (p : ℕ) [Fact (Nat.Prime p)]\n\n");

    // -- helper lemmas: extract useful equalities from each constraint
    for (c, label) in gadget.constraints.iter().zip(constraint_labels.iter()) {
        let expr = emit_constraint_expr(c, &witness_by_id)?;
        let rearranged = rearrange_constraint(c, &witness_by_id)?;

        out.push_str(&format!(
            "/-- Extract useful equality from constraint `{}`. -/\n",
            label
        ));
        out.push_str(&format!("lemma {}_extract_{}\n", gadget_ident, label));
        out.push_str(&format!("    ({} : ZMod p)\n", witness_names.join(" ")));
        out.push_str(&format!("    (h : {} = 0) :\n", expr));
        out.push_str(&format!("    {} := by\n  sorry\n\n", rearranged));
    }

    // -- main theorem
    out.push_str(&format!("theorem {}\n", theorem_name));
    out.push_str(&format!("    ({} : ZMod p)\n", witness_names.join(" ")));

    for h in &gadget.hypotheses {
        out.push_str(&format!("    ({} : {})\n", h.name, h.lean_type));
    }

    for (c, label) in gadget.constraints.iter().zip(constraint_labels.iter()) {
        let expr = emit_constraint_expr(c, &witness_by_id)?;
        out.push_str(&format!("    (h_{} : {} = 0)\n", label, expr));
    }

    let conclusion = match &gadget.soundness_spec {
        Some(spec) => format!("    : {}", spec),
        None => "    : True".to_string(),
    };
    out.push_str(&conclusion);
    out.push_str(" := by\n");

    // -- proof skeleton with helper lemma applications
    for label in &constraint_labels {
        out.push_str(&format!(
            "  have h_{}_eq := {}_extract_{} p {} h_{}\n",
            label,
            gadget_ident,
            label,
            witness_names.join(" "),
            label
        ));
    }
    out.push_str("  sorry\n");

    // -- audit gate: the main theorem (and, transitively, every helper lemma it
    // uses) must rest only on the trusted kernel axioms for the build to pass.
    out.push_str(&audit_gate(&theorem_name));

    Ok(out)
}

/// Smallest prime strictly greater than or equal to `n` (trial division —
/// refutation primes are tiny).
fn next_prime_at_least(n: u64) -> u64 {
    let mut candidate = n.max(2);
    loop {
        let mut is_prime = candidate >= 2;
        let mut d = 2u64;
        while d * d <= candidate {
            if candidate.is_multiple_of(d) {
                is_prime = false;
                break;
            }
            d += 1;
        }
        if is_prime {
            return candidate;
        }
        candidate += 1;
    }
}

/// The field size for a refutation probe: the smallest prime satisfying every
/// `p > N` hypothesis the gadget declares, and at least `min` (a floor like 5
/// keeps degenerate tiny fields out). A refutation at one valid prime refutes
/// the generic theorem.
pub fn refutation_prime(gadget: &Gadget, min: u64) -> u64 {
    let mut lower = min.max(2);
    for h in &gadget.hypotheses {
        let t = h.lean_type.trim();
        if let Some(rest) = t.strip_prefix("p").map(str::trim_start) {
            if let Some(bound) = rest.strip_prefix('>').map(str::trim) {
                if let Ok(n) = bound.parse::<u64>() {
                    lower = lower.max(n + 1);
                }
            }
        }
    }
    next_prime_at_least(lower)
}

/// Replace the standalone identifier `p` in a spec / hypothesis string with a
/// concrete prime literal (`p > 256` → `257 > 256`; `exp` stays untouched).
fn substitute_p(s: &str, prime: u64) -> String {
    let chars: Vec<char> = s.chars().collect();
    let is_ident = |c: char| c.is_alphanumeric() || c == '_' || c == '\'';
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        let standalone_p = c == 'p'
            && (i == 0 || !is_ident(chars[i - 1]))
            && (i + 1 == chars.len() || !is_ident(chars[i + 1]));
        if standalone_p {
            out.push_str(&prime.to_string());
        } else {
            out.push(c);
        }
    }
    out
}

/// Emit a **refutation scaffold**: the gadget's soundness statement at a concrete
/// small prime, negated, with a `sorry` body for the adversarial loop to fill.
///
/// ```text
/// theorem <name>_refuted :
///     ¬ (∀ (vars : ZMod <prime>), hyps → constraints → spec) := by
///   sorry
/// ```
///
/// A kernel-accepted proof of this theorem is a concrete counterexample: values
/// satisfying every constraint while violating the spec — the gadget is
/// under-constrained (or the spec is wrong). Exhausting the budget without one
/// is evidence, not proof, that the spec survives attack. The `#audit_axioms`
/// gate holds refutations to the same axiom standard as proofs.
pub fn emit_refutation(gadget: &Gadget, prime: u64) -> Result<String, EmitError> {
    let spec = gadget
        .soundness_spec
        .as_ref()
        .ok_or(EmitError::MissingSpec)?;
    let witness_names: Vec<&str> = gadget.witnesses.iter().map(|w| w.name.as_str()).collect();
    let witness_by_id = witness_map(gadget)?;
    let theorem_name = format!(
        "{}_refuted",
        sanitize_generated_ident(&gadget.name, "gadget")
    );
    let constraint_labels = generated_constraint_labels(gadget)?;
    let _ = constraint_labels; // labels documented in the header; antecedents are positional

    let mut out = String::new();

    // -- imports (same set the prover scaffolds use)
    out.push_str("import ZkGadgets.Field\n");
    out.push_str("import ZkGadgets.Audit\n");
    out.push_str("import Mathlib.Data.ZMod.Basic\n");
    out.push_str("import Mathlib.Algebra.Field.ZMod\n");
    out.push_str("import Mathlib.Tactic.Ring\n");
    out.push_str("import Mathlib.Tactic.LinearCombination\n\n");

    // -- doc comment
    out.push_str(&format!("/-!\n# {} — refutation target\n\n", gadget.name));
    out.push_str(
        "Auto-generated by lean-emit (refutation mode). Do not edit the theorem statement.\n\n",
    );
    out.push_str(&format!(
        "A kernel-accepted proof of this theorem is a concrete counterexample at\n\
         `p = {prime}`: witness values satisfying every constraint while violating the\n\
         spec. That refutes the generic soundness statement — the circuit is\n\
         under-constrained (or the spec is wrong).\n\n"
    ));
    out.push_str("Constraints:\n");
    for c in &gadget.constraints {
        out.push_str(&format!(
            "  {} : {} = 0\n",
            c.label,
            emit_constraint_expr(c, &witness_by_id)?
        ));
    }
    out.push_str(&format!("\nSpec under attack: {}\n", spec));
    out.push_str("-/\n\n");

    // -- theorem: the negated universally-quantified statement at the probe prime
    out.push_str(&format!("theorem {}\n", theorem_name));
    out.push_str(&format!(
        "    : ¬ (∀ ({} : ZMod {prime}),\n",
        witness_names.join(" ")
    ));
    for h in &gadget.hypotheses {
        out.push_str(&format!(
            "        {} →\n",
            substitute_p(&h.lean_type, prime)
        ));
    }
    for c in &gadget.constraints {
        // constraint expressions can carry `(1 : ZMod p)`-style casts
        let expr = substitute_p(&emit_constraint_expr(c, &witness_by_id)?, prime);
        out.push_str(&format!("        {} = 0 →\n", expr));
    }
    out.push_str(&format!(
        "        ({})) := by\n  sorry\n",
        substitute_p(spec, prime)
    ));

    // -- audit gate: a refutation must rest on the trusted kernel axioms too
    out.push_str(&audit_gate(&theorem_name));

    Ok(out)
}

/// Render an `#audit_axioms` gate line for a theorem. Placed after the proof so
/// `lake build` fails on an unproven or axiom-tainted scaffold rather than
/// merely warning.
fn audit_gate(theorem_name: &str) -> String {
    format!(
        "\n#audit_axioms {theorem_name}  -- proof must rest only on the trusted kernel axioms\n"
    )
}

/// Rearrange a constraint `sum_of_terms = 0` into a more useful equality.
///
/// Strategy: move negative terms to the RHS so we get `positives = negatives`.
fn rearrange_constraint(
    c: &Constraint,
    witness_by_id: &HashMap<usize, &str>,
) -> Result<String, EmitError> {
    let mut lhs_parts = Vec::new();
    let mut rhs_parts = Vec::new();

    for term in &c.terms {
        let coeff = term.coeff.trim();
        let negative = coeff.starts_with('-');
        let abs_coeff = if negative { &coeff[1..] } else { coeff };

        let monomial =
            if term.vars.is_empty() {
                None
            } else {
                let mut names = Vec::new();
                for &id in &term.vars {
                    let name = witness_by_id.get(&id).copied().ok_or_else(|| {
                        EmitError::UnknownWitnessId {
                            constraint: c.label.clone(),
                            id,
                        }
                    })?;
                    names.push(name);
                }
                Some(names.join(" * "))
            };

        let expr = match (abs_coeff, &monomial) {
            ("1", Some(m)) => m.clone(),
            (c, Some(m)) => format!("{} * {}", c, m),
            ("1", None) => "(1 : ZMod p)".to_string(),
            (c, None) => format!("({} : ZMod p)", c),
        };

        if negative {
            rhs_parts.push(expr);
        } else {
            lhs_parts.push(expr);
        }
    }

    // If everything is on one side, fall back to `expr = 0`
    if lhs_parts.is_empty() || rhs_parts.is_empty() {
        let expr = emit_constraint_expr(c, witness_by_id)?;
        return Ok(format!("{} = 0", expr));
    }

    Ok(format!(
        "{} = {}",
        lhs_parts.join(" + "),
        rhs_parts.join(" + ")
    ))
}

/// Emit a Lean 4 proof scaffold from a gadget definition.
///
/// The output contains imports, witness parameters, constraint hypotheses,
/// and a `sorry` proof. The theorem statement is machine-generated;
/// the proof is left for a human or LLM to fill in.
pub fn emit_lean(gadget: &Gadget) -> Result<String, EmitError> {
    let witness_names: Vec<&str> = gadget.witnesses.iter().map(|w| w.name.as_str()).collect();
    let witness_by_id = witness_map(gadget)?;
    let theorem_name = format!("{}_sound", sanitize_generated_ident(&gadget.name, "gadget"));
    let constraint_labels = generated_constraint_labels(gadget)?;

    let mut out = String::new();

    // -- imports
    out.push_str("import ZkGadgets.Field\n");
    out.push_str("import ZkGadgets.Audit\n");
    out.push_str("import Mathlib.Data.ZMod.Basic\n");
    out.push_str("import Mathlib.Algebra.Field.ZMod\n");
    // The tactics the system prompt teaches (`linear_combination`, `ring`) must
    // be importable, or every model proof fails with "unknown tactic".
    out.push_str("import Mathlib.Tactic.Ring\n");
    out.push_str("import Mathlib.Tactic.LinearCombination\n\n");

    // -- doc comment
    out.push_str(&format!("/-!\n# {}\n\n", gadget.name));
    out.push_str("Auto-generated by lean-emit. Do not edit the theorem statement.\n\n");
    out.push_str("Constraints:\n");
    for c in &gadget.constraints {
        out.push_str(&format!(
            "  {} : {} = 0\n",
            c.label,
            emit_constraint_expr(c, &witness_by_id)?
        ));
    }
    if let Some(spec) = &gadget.soundness_spec {
        out.push_str(&format!("\nSoundness: {}\n", spec));
    }
    out.push_str("-/\n\n");

    // -- field variable
    out.push_str("variable (p : ℕ) [Fact (Nat.Prime p)]\n\n");

    // -- theorem
    out.push_str(&format!("theorem {}\n", theorem_name));

    // witness parameters
    out.push_str(&format!("    ({} : ZMod p)\n", witness_names.join(" ")));

    // extra hypotheses (e.g. field-size bounds)
    for h in &gadget.hypotheses {
        out.push_str(&format!("    ({} : {})\n", h.name, h.lean_type));
    }

    // constraint hypotheses
    for (c, label) in gadget.constraints.iter().zip(constraint_labels.iter()) {
        let expr = emit_constraint_expr(c, &witness_by_id)?;
        out.push_str(&format!("    (h_{} : {} = 0)\n", label, expr));
    }

    // conclusion
    let conclusion = match &gadget.soundness_spec {
        Some(spec) => format!("    : {}", spec),
        None => "    : True".to_string(),
    };
    out.push_str(&conclusion);
    out.push_str(" := by\n  sorry\n");

    // -- audit gate: proof must rest only on the trusted kernel axioms
    out.push_str(&audit_gate(&theorem_name));

    Ok(out)
}

/// Render a constraint as a Lean expression (without `= 0`).
fn emit_constraint_expr(
    c: &Constraint,
    witness_by_id: &HashMap<usize, &str>,
) -> Result<String, EmitError> {
    if c.terms.is_empty() {
        return Ok("0".to_string());
    }

    let mut parts = Vec::new();
    for (i, term) in c.terms.iter().enumerate() {
        parts.push(emit_term(term, witness_by_id, &c.label, i == 0)?);
    }
    Ok(parts.join(" "))
}

/// Render a single term with sign handling.
///
/// `is_first` controls whether a leading `+` is suppressed.
fn emit_term(
    term: &Term,
    witness_by_id: &HashMap<usize, &str>,
    constraint: &str,
    is_first: bool,
) -> Result<String, EmitError> {
    let coeff = term.coeff.trim();
    let negative = coeff.starts_with('-');
    let abs_coeff = if negative { &coeff[1..] } else { coeff };

    // monomial: product of witness names
    let monomial: Option<String> = if term.vars.is_empty() {
        None
    } else {
        let mut var_names = Vec::with_capacity(term.vars.len());
        for &id in &term.vars {
            let name =
                witness_by_id
                    .get(&id)
                    .copied()
                    .ok_or_else(|| EmitError::UnknownWitnessId {
                        constraint: constraint.to_string(),
                        id,
                    })?;
            var_names.push(name);
        }
        Some(var_names.join(" * "))
    };

    // absolute expression (no sign)
    let expr = match (abs_coeff, &monomial) {
        ("1", Some(m)) => m.clone(),
        (c, Some(m)) => format!("{} * {}", c, m),
        ("1", None) => "(1 : ZMod p)".to_string(),
        (c, None) => format!("({} : ZMod p)", c),
    };

    // attach sign
    if is_first {
        if negative {
            Ok(format!("-({})", expr))
        } else {
            Ok(expr)
        }
    } else if negative {
        Ok(format!("- {}", expr))
    } else {
        Ok(format!("+ {}", expr))
    }
}

fn witness_map(gadget: &Gadget) -> Result<HashMap<usize, &str>, EmitError> {
    let mut witness_by_id = HashMap::with_capacity(gadget.witnesses.len());
    let mut witness_names = HashSet::with_capacity(gadget.witnesses.len());

    for witness in &gadget.witnesses {
        validate_user_ident("witness", &witness.name)?;
        if witness_by_id
            .insert(witness.id, witness.name.as_str())
            .is_some()
        {
            return Err(EmitError::DuplicateWitnessId(witness.id));
        }
        if !witness_names.insert(witness.name.as_str()) {
            return Err(EmitError::InvalidIdentifier {
                kind: "duplicate witness",
                name: witness.name.clone(),
            });
        }
    }

    for h in &gadget.hypotheses {
        validate_user_ident("hypothesis", &h.name)?;
    }

    Ok(witness_by_id)
}

fn generated_constraint_labels(gadget: &Gadget) -> Result<Vec<String>, EmitError> {
    let mut seen = HashSet::with_capacity(gadget.constraints.len());
    let mut labels = Vec::with_capacity(gadget.constraints.len());

    for constraint in &gadget.constraints {
        let label = sanitize_generated_ident(&constraint.label, "constraint");
        if !seen.insert(label.clone()) {
            return Err(EmitError::DuplicateConstraintLabel(label));
        }
        labels.push(label);
    }

    Ok(labels)
}

fn validate_user_ident(kind: &'static str, name: &str) -> Result<(), EmitError> {
    if is_valid_lean_ident(name) {
        Ok(())
    } else {
        Err(EmitError::InvalidIdentifier {
            kind,
            name: name.to_string(),
        })
    }
}

fn sanitize_generated_ident(input: &str, fallback: &str) -> String {
    let mut out = String::new();
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    while out.contains("__") {
        out = out.replace("__", "_");
    }

    let out = out.trim_matches('_');
    let mut out = if out.is_empty() {
        fallback.to_string()
    } else {
        out.to_string()
    };

    if out.as_bytes().first().is_some_and(u8::is_ascii_digit) || is_lean_keyword(&out) {
        out.insert_str(0, fallback);
        out.insert(fallback.len(), '_');
    }

    out
}

fn is_valid_lean_ident(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }

    if is_lean_keyword(name) {
        return false;
    }

    chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '\'')
}

fn is_lean_keyword(name: &str) -> bool {
    matches!(
        name,
        "abbrev"
            | "axiom"
            | "by"
            | "class"
            | "def"
            | "deriving"
            | "do"
            | "else"
            | "end"
            | "example"
            | "extends"
            | "for"
            | "forall"
            | "fun"
            | "have"
            | "if"
            | "import"
            | "in"
            | "inductive"
            | "infix"
            | "instance"
            | "let"
            | "macro"
            | "match"
            | "mutual"
            | "namespace"
            | "open"
            | "opaque"
            | "partial"
            | "private"
            | "protected"
            | "section"
            | "set_option"
            | "structure"
            | "syntax"
            | "theorem"
            | "unsafe"
            | "variable"
            | "where"
            | "with"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use gadget_ir::WitnessVar;

    fn examples_dir() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .join("examples")
    }

    #[test]
    fn emit_range_check() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("range-check/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();

        // has theorem with correct name
        assert!(out.contains("theorem range_check_8bit_sound"));
        // has all witnesses
        assert!(out.contains("(x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)"));
        // bit constraint renders correctly: b0 * b0 - b0 = 0
        assert!(out.contains("h_bit_0 : b0 * b0 - b0 = 0"));
        // decomposition has weighted terms
        assert!(out.contains("h_decomposition :"));
        assert!(out.contains("128 * b7"));
        assert!(out.contains("- x = 0"));
        // ends with sorry
        assert!(out.contains("sorry"));
        // non-vacuous soundness spec in conclusion, with its load-bearing bound
        assert!(out.contains("ZMod.val x < 256"));
        assert!(out.contains("(hp : p > 256)"));
        // audit gate on the theorem, with its import
        assert!(out.contains("import ZkGadgets.Audit"));
        assert!(out.trim_end().ends_with(
            "#audit_axioms range_check_8bit_sound  -- proof must rest only on the trusted kernel axioms"
        ));
    }

    #[test]
    fn refutation_prime_honors_bounds() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("range-check/gadget.toml")).unwrap();
        // hp : p > 256 forces the probe past the bound, to the next prime.
        assert_eq!(refutation_prime(&gadget, 5), 257);
        let no_hyp =
            gadget_ir::load_gadget_file(&examples_dir().join("poseidon-sbox/gadget.toml")).unwrap();
        assert_eq!(refutation_prime(&no_hyp, 5), 5);
        assert_eq!(refutation_prime(&no_hyp, 6), 7);
    }

    #[test]
    fn substitute_p_is_identifier_aware() {
        assert_eq!(substitute_p("p > 256", 257), "257 > 256");
        assert_eq!(substitute_p("(1 : ZMod p)", 5), "(1 : ZMod 5)");
        // `p` inside identifiers must survive.
        assert_eq!(substitute_p("exp + p_val + x", 5), "exp + p_val + x");
        assert_eq!(substitute_p("ZMod.val x < 256", 257), "ZMod.val x < 256");
    }

    #[test]
    fn emit_refutation_negates_statement_at_concrete_prime() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("range-check/gadget.toml")).unwrap();
        let out = emit_refutation(&gadget, 257).unwrap();

        assert!(out.contains("theorem range_check_8bit_refuted"));
        // negated ∀ at the concrete prime; no generic field variable, no Fact binder
        assert!(out.contains("¬ (∀ (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod 257),"));
        assert!(!out.contains("variable (p"));
        // the p-bound hypothesis and spec are concretized
        assert!(out.contains("257 > 256 →"));
        assert!(out.contains("(ZMod.val x < 256)) := by"));
        // constraints appear as antecedents
        assert!(out.contains("b0 * b0 - b0 = 0 →"));
        // scaffold is red until refuted, and gated
        assert!(out.contains("sorry"));
        assert!(out.trim_end().ends_with(
            "#audit_axioms range_check_8bit_refuted  -- proof must rest only on the trusted kernel axioms"
        ));
    }

    #[test]
    fn emit_refutation_requires_a_spec() {
        let gadget = Gadget {
            name: "no-spec".into(),
            modulus: "7".into(),
            soundness_spec: None,
            hypotheses: vec![],
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x".into(),
            }],
            constraints: vec![],
        };
        assert_eq!(emit_refutation(&gadget, 5), Err(EmitError::MissingSpec));
    }

    #[test]
    fn emit_conditional_select() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("conditional-select/gadget.toml"))
                .unwrap();
        let out = emit_lean(&gadget).unwrap();

        assert!(out.contains("theorem conditional_select_sound"));
        assert!(out.contains("(b x y z : ZMod p)"));
        // boolean constraint: b * b - b = 0
        assert!(out.contains("h_boolean : b * b - b = 0"));
        // select constraint: b * x + y - b * y - z = 0
        assert!(out.contains("h_select : b * x + y - b * y - z = 0"));
        assert!(out.contains("sorry"));
    }

    #[test]
    fn emit_poseidon_sbox() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("poseidon-sbox/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem poseidon_sbox_sound"));
        assert!(out.contains("(x q r y : ZMod p)"));
        assert!(out.contains("h_square_1 : q - x * x = 0"));
        assert!(out.contains("h_square_2 : r - q * q = 0"));
        assert!(out.contains("h_output : y - r * x = 0"));
        assert!(out.contains("y = x ^ 5"));
    }

    #[test]
    fn emit_nonzero_check() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("nonzero-check/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem nonzero_check_sound"));
        assert!(out.contains("h_inverse : x * x_inv - (1 : ZMod p) = 0"));
        assert!(out.contains("x ≠ 0"));
    }

    #[test]
    fn emit_edwards_addition() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("edwards-addition/gadget.toml"))
                .unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem edwards_addition_sound"));
        assert!(out.contains("(x1 y1 x2 y2 x3 y3 : ZMod p)"));
        // hypotheses before constraints
        assert!(out.contains("h_on_curve_1"));
        assert!(out.contains("h_on_curve_2"));
        assert!(out.contains("h_nondeg_x"));
        assert!(out.contains("h_nondeg_y"));
        assert!(out.contains("h_add_x"));
        assert!(out.contains("h_add_y"));
        assert!(out.contains("168700"));
    }

    #[test]
    fn emit_range_check_with_hypothesis() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("range-check/gadget.toml")).unwrap();
        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("(hp : p > 256)"));
        // hypothesis appears before constraints
        let hp_pos = out.find("hp : p > 256").unwrap();
        let hbit_pos = out.find("h_bit_0").unwrap();
        assert!(hp_pos < hbit_pos);
    }

    #[test]
    fn emits_terms_by_witness_id_not_position() {
        let gadget = Gadget {
            name: "out-of-order".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![
                WitnessVar {
                    id: 10,
                    name: "x".to_string(),
                },
                WitnessVar {
                    id: 3,
                    name: "y".to_string(),
                },
            ],
            constraints: vec![Constraint {
                label: "product".to_string(),
                terms: vec![Term {
                    coeff: "1".to_string(),
                    vars: vec![3, 10],
                }],
            }],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("h_product : y * x = 0"));
    }

    #[test]
    fn rejects_unknown_witness_id() {
        let gadget = Gadget {
            name: "bad-ref".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x".to_string(),
            }],
            constraints: vec![Constraint {
                label: "missing".to_string(),
                terms: vec![Term {
                    coeff: "1".to_string(),
                    vars: vec![1],
                }],
            }],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let err = emit_lean(&gadget).unwrap_err();
        assert!(matches!(err, EmitError::UnknownWitnessId { id: 1, .. }));
    }

    #[test]
    fn rejects_invalid_user_identifier() {
        let gadget = Gadget {
            name: "bad-ident".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x-bad".to_string(),
            }],
            constraints: vec![],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let err = emit_lean(&gadget).unwrap_err();
        assert!(matches!(
            err,
            EmitError::InvalidIdentifier {
                kind: "witness",
                ..
            }
        ));
    }

    #[test]
    fn decompose_edwards_addition() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("edwards-addition/gadget.toml"))
                .unwrap();
        let out = emit_lean_decomposed(&gadget).unwrap();
        // Should have helper lemmas
        assert!(out.contains("lemma edwards_addition_extract_add_x"));
        assert!(out.contains("lemma edwards_addition_extract_add_y"));
        // Helper lemmas should have rearranged equalities
        assert!(out.contains("= x1 * y2 + y1 * x2")); // add_x positive terms
        assert!(out.contains("168696 * y3 * x1 * x2 * y1 * y2 + y1 * y2")); // add_y RHS
                                                                            // Main theorem should reference helpers
        assert!(out.contains("h_add_x_eq := edwards_addition_extract_add_x"));
        assert!(out.contains("h_add_y_eq := edwards_addition_extract_add_y"));
        // Still has the main theorem
        assert!(out.contains("theorem edwards_addition_sound"));
    }

    #[test]
    fn decompose_poseidon_sbox() {
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("poseidon-sbox/gadget.toml")).unwrap();
        let out = emit_lean_decomposed(&gadget).unwrap();
        assert!(out.contains("lemma poseidon_sbox_extract_square_1"));
        assert!(out.contains("lemma poseidon_sbox_extract_square_2"));
        assert!(out.contains("lemma poseidon_sbox_extract_output"));
        // Rearranged: q = x * x, r = q * q, y = r * x
        assert!(out.contains("q = x * x"));
        assert!(out.contains("r = q * q"));
        assert!(out.contains("y = r * x"));
        // One audit gate, on the main theorem (helpers are covered transitively).
        assert_eq!(out.matches("#audit_axioms").count(), 1);
        assert!(out.contains("#audit_axioms poseidon_sbox_sound"));
    }

    #[test]
    fn decompose_skips_simple_gadgets() {
        // nonzero-check has only 1 constraint, should fall back to emit_lean
        let gadget =
            gadget_ir::load_gadget_file(&examples_dir().join("nonzero-check/gadget.toml")).unwrap();
        let out = emit_lean_decomposed(&gadget).unwrap();
        // Should NOT have extract lemmas
        assert!(!out.contains("extract_"));
        // Should have the normal theorem
        assert!(out.contains("theorem nonzero_check_sound"));
    }

    #[test]
    fn sanitizes_generated_identifiers() {
        let gadget = Gadget {
            name: "8-bit gadget!".to_string(),
            modulus: "17".to_string(),
            witnesses: vec![WitnessVar {
                id: 0,
                name: "x".to_string(),
            }],
            constraints: vec![Constraint {
                label: "select-value!".to_string(),
                terms: vec![Term {
                    coeff: "1".to_string(),
                    vars: vec![0],
                }],
            }],
            hypotheses: vec![],
            soundness_spec: None,
        };

        let out = emit_lean(&gadget).unwrap();
        assert!(out.contains("theorem gadget_8_bit_gadget_sound"));
        assert!(out.contains("h_select_value : x = 0"));
    }
}
