import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# conditional-select

Auto-generated by lean-emit (decomposed mode). Do not edit the theorem statement.

Constraints:
  boolean : b * b - b = 0
  select : b * x + y - b * y - z = 0

Soundness: (b = 0 ∧ z = y) ∨ (b = 1 ∧ z = x)
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

/-- Extract useful equality from constraint `boolean`. -/
lemma conditional_select_extract_boolean
    (b x y z : ZMod p)
    (h : b * b - b = 0) :
    b * b = b := by
  sorry

/-- Extract useful equality from constraint `select`. -/
lemma conditional_select_extract_select
    (b x y z : ZMod p)
    (h : b * x + y - b * y - z = 0) :
    b * x + y = b * y + z := by
  sorry

theorem conditional_select_sound
    (b x y z : ZMod p)
    (h_boolean : b * b - b = 0)
    (h_select : b * x + y - b * y - z = 0)
    : (b = 0 ∧ z = y) ∨ (b = 1 ∧ z = x) := by
  have h_boolean_eq := conditional_select_extract_boolean p b x y z h_boolean
  have h_select_eq := conditional_select_extract_select p b x y z h_select
  sorry

#audit_axioms conditional_select_sound  -- proof must rest only on the trusted kernel axioms
