import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# conditional-select

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  boolean : b * b - b = 0
  select : b * x + y - b * y - z = 0

Soundness: (b = 0 ∧ z = y) ∨ (b = 1 ∧ z = x)
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem conditional_select_sound
    (b x y z : ZMod p)
    (h_boolean : b * b - b = 0)
    (h_select : b * x + y - b * y - z = 0)
    : (b = 0 ∧ z = y) ∨ (b = 1 ∧ z = x) := by
  sorry

#audit_axioms conditional_select_sound  -- proof must rest only on the trusted kernel axioms
