import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# edwards-addition

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  add_x : x3 + 168696 * x3 * x1 * x2 * y1 * y2 - x1 * y2 - y1 * x2 = 0
  add_y : y3 - 168696 * y3 * x1 * x2 * y1 * y2 - y1 * y2 + 168700 * x1 * x2 = 0

Soundness: 168700 * x3 * x3 + y3 * y3 = 1 + 168696 * x3 * x3 * y3 * y3
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem edwards_addition_sound
    (x1 y1 x2 y2 x3 y3 : ZMod p)
    (h_on_curve_1 : (168700 : ZMod p) * x1 * x1 + y1 * y1 = 1 + (168696 : ZMod p) * x1 * x1 * y1 * y1)
    (h_on_curve_2 : (168700 : ZMod p) * x2 * x2 + y2 * y2 = 1 + (168696 : ZMod p) * x2 * x2 * y2 * y2)
    (h_nondeg_x : (1 : ZMod p) + (168696 : ZMod p) * x1 * x2 * y1 * y2 ≠ 0)
    (h_nondeg_y : (1 : ZMod p) - (168696 : ZMod p) * x1 * x2 * y1 * y2 ≠ 0)
    (h_add_x : x3 + 168696 * x3 * x1 * x2 * y1 * y2 - x1 * y2 - y1 * x2 = 0)
    (h_add_y : y3 - 168696 * y3 * x1 * x2 * y1 * y2 - y1 * y2 + 168700 * x1 * x2 = 0)
    : 168700 * x3 * x3 + y3 * y3 = 1 + 168696 * x3 * x3 * y3 * y3 := by
  sorry

#audit_axioms edwards_addition_sound  -- proof must rest only on the trusted kernel axioms
