import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# nonzero-check

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  inverse : x * x_inv - (1 : ZMod p) = 0

Soundness: x ≠ 0
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem nonzero_check_sound
    (x x_inv : ZMod p)
    (h_inverse : x * x_inv - (1 : ZMod p) = 0)
    : x ≠ 0 := by
  sorry

#audit_axioms nonzero_check_sound  -- proof must rest only on the trusted kernel axioms
