import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# poseidon-sbox

Auto-generated by lean-emit (decomposed mode). Do not edit the theorem statement.

Constraints:
  square_1 : q - x * x = 0
  square_2 : r - q * q = 0
  output : y - r * x = 0

Soundness: y = x ^ 5
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

/-- Extract useful equality from constraint `square_1`. -/
lemma poseidon_sbox_extract_square_1
    (x q r y : ZMod p)
    (h : q - x * x = 0) :
    q = x * x := by
  sorry

/-- Extract useful equality from constraint `square_2`. -/
lemma poseidon_sbox_extract_square_2
    (x q r y : ZMod p)
    (h : r - q * q = 0) :
    r = q * q := by
  sorry

/-- Extract useful equality from constraint `output`. -/
lemma poseidon_sbox_extract_output
    (x q r y : ZMod p)
    (h : y - r * x = 0) :
    y = r * x := by
  sorry

theorem poseidon_sbox_sound
    (x q r y : ZMod p)
    (h_square_1 : q - x * x = 0)
    (h_square_2 : r - q * q = 0)
    (h_output : y - r * x = 0)
    : y = x ^ 5 := by
  have h_square_1_eq := poseidon_sbox_extract_square_1 p x q r y h_square_1
  have h_square_2_eq := poseidon_sbox_extract_square_2 p x q r y h_square_2
  have h_output_eq := poseidon_sbox_extract_output p x q r y h_output
  sorry

#audit_axioms poseidon_sbox_sound  -- proof must rest only on the trusted kernel axioms
