import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# range-check-8bit

Auto-generated by lean-emit (decomposed mode). Do not edit the theorem statement.

Constraints:
  bit_0 : b0 * b0 - b0 = 0
  bit_1 : b1 * b1 - b1 = 0
  bit_2 : b2 * b2 - b2 = 0
  bit_3 : b3 * b3 - b3 = 0
  bit_4 : b4 * b4 - b4 = 0
  bit_5 : b5 * b5 - b5 = 0
  bit_6 : b6 * b6 - b6 = 0
  bit_7 : b7 * b7 - b7 = 0
  decomposition : b0 + 2 * b1 + 4 * b2 + 8 * b3 + 16 * b4 + 32 * b5 + 64 * b6 + 128 * b7 - x = 0

Soundness: ZMod.val x < 256
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

/-- Extract useful equality from constraint `bit_0`. -/
lemma range_check_8bit_extract_bit_0
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b0 * b0 - b0 = 0) :
    b0 * b0 = b0 := by
  sorry

/-- Extract useful equality from constraint `bit_1`. -/
lemma range_check_8bit_extract_bit_1
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b1 * b1 - b1 = 0) :
    b1 * b1 = b1 := by
  sorry

/-- Extract useful equality from constraint `bit_2`. -/
lemma range_check_8bit_extract_bit_2
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b2 * b2 - b2 = 0) :
    b2 * b2 = b2 := by
  sorry

/-- Extract useful equality from constraint `bit_3`. -/
lemma range_check_8bit_extract_bit_3
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b3 * b3 - b3 = 0) :
    b3 * b3 = b3 := by
  sorry

/-- Extract useful equality from constraint `bit_4`. -/
lemma range_check_8bit_extract_bit_4
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b4 * b4 - b4 = 0) :
    b4 * b4 = b4 := by
  sorry

/-- Extract useful equality from constraint `bit_5`. -/
lemma range_check_8bit_extract_bit_5
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b5 * b5 - b5 = 0) :
    b5 * b5 = b5 := by
  sorry

/-- Extract useful equality from constraint `bit_6`. -/
lemma range_check_8bit_extract_bit_6
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b6 * b6 - b6 = 0) :
    b6 * b6 = b6 := by
  sorry

/-- Extract useful equality from constraint `bit_7`. -/
lemma range_check_8bit_extract_bit_7
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b7 * b7 - b7 = 0) :
    b7 * b7 = b7 := by
  sorry

/-- Extract useful equality from constraint `decomposition`. -/
lemma range_check_8bit_extract_decomposition
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (h : b0 + 2 * b1 + 4 * b2 + 8 * b3 + 16 * b4 + 32 * b5 + 64 * b6 + 128 * b7 - x = 0) :
    b0 + 2 * b1 + 4 * b2 + 8 * b3 + 16 * b4 + 32 * b5 + 64 * b6 + 128 * b7 = x := by
  sorry

theorem range_check_8bit_sound
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (hp : p > 256)
    (h_bit_0 : b0 * b0 - b0 = 0)
    (h_bit_1 : b1 * b1 - b1 = 0)
    (h_bit_2 : b2 * b2 - b2 = 0)
    (h_bit_3 : b3 * b3 - b3 = 0)
    (h_bit_4 : b4 * b4 - b4 = 0)
    (h_bit_5 : b5 * b5 - b5 = 0)
    (h_bit_6 : b6 * b6 - b6 = 0)
    (h_bit_7 : b7 * b7 - b7 = 0)
    (h_decomposition : b0 + 2 * b1 + 4 * b2 + 8 * b3 + 16 * b4 + 32 * b5 + 64 * b6 + 128 * b7 - x = 0)
    : ZMod.val x < 256 := by
  have h_bit_0_eq := range_check_8bit_extract_bit_0 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_0
  have h_bit_1_eq := range_check_8bit_extract_bit_1 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_1
  have h_bit_2_eq := range_check_8bit_extract_bit_2 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_2
  have h_bit_3_eq := range_check_8bit_extract_bit_3 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_3
  have h_bit_4_eq := range_check_8bit_extract_bit_4 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_4
  have h_bit_5_eq := range_check_8bit_extract_bit_5 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_5
  have h_bit_6_eq := range_check_8bit_extract_bit_6 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_6
  have h_bit_7_eq := range_check_8bit_extract_bit_7 p x b0 b1 b2 b3 b4 b5 b6 b7 h_bit_7
  have h_decomposition_eq := range_check_8bit_extract_decomposition p x b0 b1 b2 b3 b4 b5 b6 b7 h_decomposition
  sorry

#audit_axioms range_check_8bit_sound  -- proof must rest only on the trusted kernel axioms
