import ZkGadgets.Field
import ZkGadgets.Audit
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Field.ZMod
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination

/-!
# range-check-8bit

Auto-generated by lean-emit. Do not edit the theorem statement.

Constraints:
  bit_0 : b0 * b0 - b0 = 0
  bit_1 : b1 * b1 - b1 = 0
  bit_2 : b2 * b2 - b2 = 0
  bit_3 : b3 * b3 - b3 = 0
  bit_4 : b4 * b4 - b4 = 0
  bit_5 : b5 * b5 - b5 = 0
  bit_6 : b6 * b6 - b6 = 0
  bit_7 : b7 * b7 - b7 = 0
  decomposition : b0 + 2 * b1 + 4 * b2 + 8 * b3 + 16 * b4 + 32 * b5 + 64 * b6 + 128 * b7 - x = 0

Soundness: ZMod.val x < 256
-/

variable (p : ℕ) [Fact (Nat.Prime p)]

theorem range_check_8bit_sound
    (x b0 b1 b2 b3 b4 b5 b6 b7 : ZMod p)
    (hp : p > 256)
    (h_bit_0 : b0 * b0 - b0 = 0)
    (h_bit_1 : b1 * b1 - b1 = 0)
    (h_bit_2 : b2 * b2 - b2 = 0)
    (h_bit_3 : b3 * b3 - b3 = 0)
    (h_bit_4 : b4 * b4 - b4 = 0)
    (h_bit_5 : b5 * b5 - b5 = 0)
    (h_bit_6 : b6 * b6 - b6 = 0)
    (h_bit_7 : b7 * b7 - b7 = 0)
    (h_decomposition : b0 + 2 * b1 + 4 * b2 + 8 * b3 + 16 * b4 + 32 * b5 + 64 * b6 + 128 * b7 - x = 0)
    : ZMod.val x < 256 := by
  sorry

#audit_axioms range_check_8bit_sound  -- proof must rest only on the trusted kernel axioms
